# Generated by Django 2.0.5 on 2018-05-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffrequest',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diffrequest',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
