# Generated by Django 2.0.5 on 2018-05-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0002_auto_20180514_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffrequest',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
