# Generated by Django 2.0.5 on 2018-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0003_auto_20180514_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffrequest',
            name='occurrences',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
