# Generated by Django 2.0.5 on 2018-05-14 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0004_auto_20180514_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffrequest',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diffrequest',
            name='value',
            field=models.IntegerField(),
        ),
    ]
